on: workflow_dispatch
#  schedule: 
#    - cron: "0 0 * * *"
name: Update chain.json
jobs:
  update_chainjson:
    name: Update chains' chain.json
    runs-on: ubuntu-latest
    steps:
      - name: checkout registry
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run:  |
          python -m pip install --upgrade pip
          cd .github/workflows/utility
          python -m pip install requests

      - name: Check chain JSON Update
        shell: python
        run: |
          import sys
          sys.path.insert(1, '.github/workflows/utility')
          import update_chaindata
          update_chaindata.checkUpdate()

      - name: Add Commit Push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_prefix: "[AUTO]"
          commit_message: "Chain.json automatic update"
          force: false
          target_branch: update/version