on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_pathsjson:
    name: Validate ibc data schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate IBC data schemas
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./ibc_data.schema.json
          json_path_pattern: ^_IBC\/.*\.json$